"""Add hours to User

Revision ID: 3504badcf1b3
Revises: 1af797eaf824
Create Date: 2021-12-29 15:15:08.118944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3504badcf1b3'
down_revision = '1af797eaf824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hours', sa.BIGINT(), nullable=True))
    op.add_column('users', sa.Column('hours_description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('hours_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hours_date')
    op.drop_column('users', 'hours_description')
    op.drop_column('users', 'hours')
    # ### end Alembic commands ###
