"""Make hours a separate table

Revision ID: cb3ab571376c
Revises: 3504badcf1b3
Create Date: 2021-12-29 16:16:40.646409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb3ab571376c'
down_revision = '3504badcf1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hours',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('quantity', sa.BIGINT(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'hours_date')
    op.drop_column('users', 'hours_description')
    op.drop_column('users', 'hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hours', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hours_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hours_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('hours')
    # ### end Alembic commands ###
